jetstream/cli.py

This allows the user to specify whether the test stack/bucket should be
cleaned up on pass or failure of a test. It defaults to pass to keep the
original functionality.

Added Clean On Condition argument

---

jetstream/testing.py

This only sets the parameters kwarg on a stack if parameters exist.

Don't set empty params in test stack

---

circle.yml
jetstream/template.py

Show the actual class name of the Jetstream template subclass when there's an error in JSON parsing or the `.to_json()` method. This helps immensely if there's an issue in building the template; without it, there's no way to know which template broke.

Print template class name with errors

---

requirements.txt
setup.py

```
Release 1.8.2
Add SpotPrice to SpotFleet LaunchSpecifications
Add new properties to ECS (Clustername to Cluster and Family to TaskDefinition)
Add Alias object to KMS (fixes #568)
Added cross-stack references (#569)
Handle lambda => awslambda mapping in cfn2py (#573)
Add support for Tags to Certificate Manager Certificates (#574)
Adding enhanced monitoring to rds.DBInstance (#575)
Add support for LogGroupName in Logs::LogGroup (#576)
Update Export param (#579)
Add support for Fn::Sub (#582)
RDS DBInstance Engine required even when DBSnapshotIdentifier is set (#583)
Resource updates for 2016-10-06 changes (Fixes #584)
Add AWS::ApiGateway::UsagePlan (fixes #585)
Add AWS::CodeCommit::Repository (fixes #586)
Provide better type checking for values in from_dict (#587)
Allow HelperFn in …
```

Upgrade to Troposphere 1.8.2

---

jetstream/template.py

Changing the indent on the JSON output to 2.
https://github.com/rax-brazil/TroposphereTemplates/issues/87

Change indent to 2

---

requirements.txt
setup.py

```
1.9.0 (2016-11-15)
Note: the dynamodb change below may cause backwards compatibility issues. There have been deprecation warnings for a while.
Replace dynamodb module with dynamodb2 (#564)
Add CodeCommit as a supported AWS resource type
Add update of github Releases page to RELEASE doc
Update elasticache for 2016-10-12 changes (#592)
Support for S3 Lifecycle Rule property NoncurrentVersionTransitions (#596)
Include resource title in required attr exception (#597)
Added Placement class for the Placement property in LaunchSpecifications. (#598)
Add EFS example (#601)
Add support to old mysql db engine (#602)
Fix typo in Example Allowed Values (#603)
Remove title validation. Fixes #428 (#605)
Add support for conditions in cfn2py script (#606)
Added MongoDB default port to constants …
```

Upgrade Troposphere and boto3

---

README.md
jetstream/template.py
jetstream/testing.py

Introduce prepare hooks that subclasses can use, for the three operations it performs (documentation, template generation, and testing).

Add prepare hooks for jetstream operations

---

requirements.txt
setup.py

```
1.9.1 (2017-01-03)
Improve readability of AssumeRolePolicyDocument attribute (#591)
Add Environment to Lambda Function (#616)
Adding DataSources to OpsWorks App and RdsDbInstances to OpsWorks Stack (#621)
Added SNS::Subscription resource (SubscriptionResource) (#622)
Added CodeBuild Project resource and a CodeBuild example (#624)
Add back support for Python 2.6 (#626)
Fixed missing add_resource in example Cloudwatch rule (#629)
Create new property Environment for aws lambda Function (#631)
Add KmsKeyArn to Lambda Function
Add CopyTagsToSnapshot to RDS::DBInstance
Fix pycodestyle issues with examples/Lambda.py
Add AWS::SSM::Association
Add AWS::EC2::SubnetCidrBlock and AWS::EC2::VPCCidrBlock
Add mutually_exclusive validator
Add DocumentType to AWS::SSM::Document
Add OpsWorks Resources: …
```

Update Troposphere to 1.9.1

---

jetstream/cli.py
jetstream/testing.py

Try to build the master template, even if we don't actually run tests, so that we catch TestParameters and things that don't serialize. This helps us find errors locally before they run in CI.

Catch more JSON serialization errors

---

jetstream/template.py

This raises an error if the Test Parameter is anything other than a string to prevent invalid master templates that cannot be marshalled.

Catch invalid types passed to the TestingParameter

---

jetstream/cli.py

There is an expectation that AWS credentials and region are set
when actually running a test with Jetstream but not when executing
Jetstream locally to generate templates. The recent change to
always generate a master test template despite not initiating a test
breaks this behavior and jetstream will now error out if credentials and
a region are not set.

Revert always generating test parent template

---

jetstream/template.py

This fixes the issue in #29 where markdown is not properly rendered
in GitHub.

Adding newline before each parameter heading

---

jetstream/template.py

This closes #29. Fixes the issue where the output
heading doesn't render properly when viewed in
GitHub.

Fixing md rendering for outputs

---

jetstream/template.py
jetstream/testing.py
test_templates/ec2_instance.py
test_templates/s3_bucket.py

This adds the ability to set up multiple Test Parameter groups which in
turn allows setting up multiple tests for each template with different
parameters. This change also allows templates dependent on these test
templates to reference test parameter groups.

Add support for multiple Test Parameter Groups

---

jetstream/testing.py

- Call test_param_group a parameter group, not a parameter, since that's what it is now.

Slight tweak to naming

---

jetstream/publisher.py
jetstream/testing.py

Requires a correct S3 path to publish templates to but adds the ability
to publish templates into S3 with a directory structure such as
s3://mycftemplates/production/templates.

Support publishing to specific S3 Path

---

jetstream/publisher.py

Actually checks whether the bucket exists rather than always returning true.

Implement publisher bucket check

---

jetstream/publisher.py

Bucket validation will no longer happen on the S3Publisher Init and
instead will happen when the Publisher attempts to access the bucket.

Move bucket validation to prevent testing exceptions

---

jetstream/cli.py

- Add a signal handler for SIGTERM
- Call sys.exit in the handler, throwing SystemExit and triggering the cleanup code.
I confirmed this worked locally using `kill -TERM <pid>` while running the testing locally.

Handle SIGTERM and clean up work

---

requirements.txt
setup.py

```
1.9.3 (2017-04-13)
Fix pycodestyle by using an explicit exception type
Add more details to pycodestyle errors for travis runs
Fix validator function exception test
Remove limit check on conditions - Fixes #657
Allow valid value for TargetGroup HealthCheckPort (#659)
Added step functions and basic tests (#661)
Adding example for CloudTrail (from http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-trail.html) (#667)
Fix ApiGateway.py sample (#666)
Update comment on type checking
Added missing props to ec2.NetworkInterfaces (#669) (#670)
Add WAF Common Attacks Sample (#675)
Updated constants with new instance types (#674)
SSM Targets - fix spelling mistake (Value => Values) (#673)
Do json validation on ApiGateway::Model Schema (Fix #679) (#681)
SQS: Add …
```

Update Troposphere to 1.9.3

---

jetstream/template.py

Add spaces after header hash symbols, to be sure they render correctly in Github.
Fixes #49.

Properly format markdown

---

jetstream/cli.py
jetstream/publisher.py
jetstream/template.py

- In publisher, fall back to a string diff when json module produces 'No JSON object could be decoded', fixes #52.
- Strip last updated from templates, so they aren't always changed
- In cli, track and check for updates to documentation separately from templates, fixes #53.

Don't load all files as JSON when checking for changes

---

jetstream/publisher.py

Be sure to close filehandle, part of eb3c39fee927b6a9db4befe7a9cb88352f498329. RE: #53, #54

Be sure to close file handle

---

jetstream/cli.py
jetstream/template.py
requirements.txt
setup.py

- Add new CLI option `-f` or `--format`, legal values are `yaml` or `json`, default to `json`
- Add cfn_flip to produce YAML from JSON, currently recommended way (RE: https://github.com/cloudtools/troposphere/issues/567)
- Add conditional for the new CLI option; tested & confirmed YAML is produced

Add optional format selector for YAML or JSON

---

requirements.txt
setup.py

```
1.9.5 (2017-07-26)
Add support for latest Cloudwatch alarms properties (#694)
Raise ValueError for Outputs and Mappings - Fix Issue #732 (#733)
Add AWS::EMR::SecurityConfiguration support (#738)
Create CODE_OF_CONDUCT.md (#740)
Added UsagePlans to API Gateway example (#741)
EMR AutoScaling Complex Validation and Introduction of an ignore validator type (#743)
Add PrivilegedMode option to CodeBuild Environments (#744)
EFS DependsOn Ref to object fix (#746)
README - add syntax highlighting (#747)
Make handling of DependsOn more pythonic (#748)
Accept Join type as parameter default value as it returns a string (#752)
AWS SAM support (#754)
Fixed UsagePlan example to proper Ref (#755)
Fix cognito StringAttributeConstraints property names (Fixes #756)
Add 'SourceAuth' property to CodeBuild …
```

Update Troposphere to 1.9.5

---

requirements.txt
setup.py

```
1.9.6 (2017-09-24)
Added missing EU_WEST_2 constants. (#776)
Override object validation (#780)
Update PyPI Information (#785)
Adding IPv6 changes to AWS::EC2::Subnet (#786)
NetworkACL Protocl Constants (#787)
Add support for EFS encryption (#789)
Add AWS::ApiGateway::GatewayResponse (#790)
Add support for aurora-postgresql as a valid DB engine (#791)
adding sqs server side encryption (#793)
Support new code deploy options (#794)
Add AWS Batch Support (#796)
VPC expansion support (#797)
Add NLB Functionality (#806)
Fix typos in examples/DynamoDB_Table.py (#807)
Revert "Accept Join type as parameter default value as it returns a string (#752)" (#808)
Change Cognito UserPool SchemaAttribute required value to boolean (#809)
Updating case of 'AssignIPv6AddressOnCreation' (#810)
Fix …
```

Update to Troposphere 1.9.6

---

requirements.txt
setup.py

awacs is likely a holdover dependency from a previous incarnation of
this project that was never cleaned up. No code is importing it or
referencing it so it should not be listed as a dependency.

Remove unused dependency

---

requirements.txt
setup.py

Fixes a number of bugs we filed upstream:
https://github.com/cloudtools/troposphere/issues/868
and
https://github.com/cloudtools/troposphere/pull/877

Troposphere released v2.1.0

---

jetstream/template.py

Provides class name to make it easier to determine which template
is missing the required attribute.

Add Class name to the Required Attrs exception message

---

requirements.txt
setup.py

Unpinning CFN Flip since it is pulled in by troposphere and bumping
troposphere to latest stable.

Update dependency versions

---

requirements.txt
setup.py

This will allow more recent versions of boto3 to be used, and allows access to recently implemented methods in projects utilizing jetstream.

Adjust boto3 pinning to allow more recent versions

---

jetstream/testing.py

I've recently seen cases where the S3 bucket name used for testing purposes conflicts. This looks to resolve the issue by adding more randomness to the bucket name through:
* Using a more detailed timestamp string
* Add additional character randomness

Ensure further randomization on test bucket naming

---

jetstream/template.py

Explicitly sets a Retention Policy of `Delete`.
Tested and confirmed RDS instances will no longer snapshot on deletion, which should help to alleviate the  failures deleting option groups.
Change necessitated by AWS changing the default behavior of some resources, such as RDS instances and Clusters.  See [DeletionPolicy attribute](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html#aws-attribute-deletionpolicy-options) for more details on the behaviors.

Update tests to explicitly set a retention policy of Delete

---

jetstream/__init__.py
jetstream/cli.py
jetstream/publisher.py
jetstream/template.py

This PR essentially adds the following:
* A top level key defined in `__init__.py` since it is used across multiple files in the jetstream module (currently set to `Jetstream`
* Code to remove toplevel key from metadata during comparison 
* A CLI option (`--metadata` or `-M`) to accept ad-hoc metadata for inserting into the top level key
Normally I'm a fan of squashing linting type fixes into commits, but there were enough to where doing so would have just made the commit history very confusing. The following checks were causing CI issues and were remediated:
* Import check for the top level metadata key. Just needed to go after boto imports.
* Fixing a too long line that didn't show any issues in the IDE. Might be a off by one error but addressed anyways.
* Fixed setting default value to …

Addition of functionality to support ad-hoc metadata which is ignored during template compare

---

CHANGELOG.md
jetstream/__init__.py

* Addition of CHANGELOG which will start at the last ad-hoc metadata commit for now
* Bump version to 0.1.1

Release 0.1.1

---

CHANGELOG.md
jetstream/__init__.py
setup.py

* Bump to 0.2.0, due to the critical code reform
* Add entry to CHANGELOG
* Add Python 3.7 to metadata entry in setup.py

[ #91 ] Update jetstream to support python 2/3

---

.circleci/config.yml
requirements.txt

* Install `cfn-flip` before troposphere since it uses a fairly greedy version deceleration when we have it pinned to a specific version

[ #94 ] Fix `cfn-flip` install order

---

CHANGELOG.md
jetstream/__init__.py

This includes the fix for making sure that `cfn-flip` version pinning works properly

Version bump to 0.2.1

---

jetstream/publisher.py

* This is due to the fact that Python3 has a different exception message but the exception itself is a base class of ValueError so this will make it more generic

[ #98 ] Make exception catch for ValueError more generic

---

jetstream/testing.py

This change should adjust the returned value to work around the issue reported in #102

Update S3 region check to handle us-east-1
